_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
Barrier:
    value: true
domain:
    value:
        "N": 1500
hyperparameters:
    value:
        alpha: 0.0001
        decay_cut: 2
        decay_init: 1
        decay_l0: 1
        decay_l2: 0.0001
        decay_lb: 3
        decay_lv: 1.5
        decay_mse: 1
        decay_tune: 2
        decay_unsafe: 1
        decay_vpos: 0.5
        epi_bound: 0.05
        epsilon_b: 0.001
        epsilon_v: 0.001
        eta: 0.01
        n_counter_examples: 20
init:
    value:
        "N": 1500
        radius: 0.1
model_b:
    value:
        activation_function: Tanh
        batch_size: 10000
        hidden_neurons: 32
        layers: 2
        learning_rate: 0.001
        max_iters: 50000
model_f:
    value:
        activation_function: Tanh
        batch_size: 512
        epochs_warm: 500
        hidden_neurons: 32
        layers: 2
        learning_rate: 0.01
model_v:
    value:
        activation_function: Tanh
        batch_size: 512
        batch_size_training: 512
        hidden_neurons: 64
        layers: 1
        learning_rate: 0.005
        max_iters: 20000
        scheduler:
            end_factor: 0.01
            start_factor: 1
plots:
    value: true
plotting:
    value:
        contour: false
        legend: false
        name: Leaf2 LASA without Obstacles
        range:
            - - -1.5
              - 0.5
            - - -0.5
              - 0.5
unsafe:
    value:
        "N": 1500
        centre:
            - -0.5
            - 0.25
        radius: 0.15
        shape: Circle
